### ISSUE TITLE
Create an IPFS demo for rust

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/ipfs-http-client#10]

**Comment by cbrzn** [comment]
in order to achieve this we need the rust client packages in crates.io - I will do this ASAP

**Comment by cbrzn** [comment]
now that the crates has been released, this has been updated and it's almost working in this branch: https://github.com/polywrap/ipfs/tree/rust-demo-fix. currently blocked by https://github.com/polywrap/rust-client/issues/59
